[tool.pytest.ini_options]
pythonpath = ["."]

[tool.black]
line-length = 79
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 79

[tool.flake8]
max-line-length = 79
exclude = [
    "venv",
    "__pycache__",
    ".git",
    ".github",
    ".ipynb_checkpoints",
]
